version: '3.8'

services:
  airflow:
    build: .
    command: standalone
    ports:
      - "8080:8080"
    volumes:
      - ./dags:/opt/airflow/dags
      - ./properties.db:/opt/airflow/properties.db
    environment:
      AIRFLOW_UID: "503"
      AIRFLOW__CORE__LOAD_EXAMPLES: "false"
      PYTHONWARNINGS: "ignore::SyntaxWarning"