version: '3.8'
services:
  airflow:
    image: apache/airflow:3.0.2  # Matches your Airflow version
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: sqlite:////usr/local/airflow/airflow.db  # Simple SQLite DB
      AIRFLOW__CORE__LOAD_EXAMPLES: 'false'  # Skip example DAGs
      AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION: 'true'
    volumes:
      - ./dags:/opt/airflow/dags  # Mount your DAGs and modules
      - ./requirements.txt:/requirements.txt  # For custom deps
    ports:
      - "8080:8080"  # Airflow UI
    command: standalone  # Runs webserver, scheduler, and init in one container
    user: "${AIRFLOW_UID:-50000}:0"  # Avoid permission issues
