services:
  postgres:
    image: postgres:14
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - postgres
  
  spark:
    image: bitnami/spark:latest
    environment:
      - SPARK_MODE=master
    ports:
      - "7077:7077"
      - "8081:8080"
    volumes:
      - ./spark-app:/opt/spark-app
      - ./spark-app/data_land_registry:/opt/spark-data  
      - ./dags/data:/opt/spark-dags-data
      - ./output:/opt/airflow/output
  
  airflow:
    build: .
    restart: always
    ports:
      - "8080:8080"
    volumes:
      - ./entrypoint.sh:/opt/airflow/entrypoint.sh
      - ./dags:/opt/airflow/dags
      - ./dags/data:/opt/airflow/dags/data 
      - ./terraform/keys:/opt/airflow/terraform/keys
      - ./output:/opt/airflow/output
      - /var/run/docker.sock:/var/run/docker.sock
      - ./spark-app/data_land_registry:/opt/spark-data
      - ./dags/data:/opt/spark-dags-data

    environment:
      AIRFLOW_UID: "503"
      AIRFLOW__CORE__LOAD_EXAMPLES: "false"
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres/airflow
      GOOGLE_APPLICATION_CREDENTIALS: /opt/airflow/terraform/keys/my-creds.json
    depends_on:
      - postgres
    entrypoint: /opt/airflow/entrypoint.sh

volumes:
  postgres_data:
