name: Deploy to Astronomer
on:
  push:
    branches: [main]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Deploy to Astro
      uses: astronomer/deploy-action@v0.3
      with:
        api-key: eyJhbGciOiJSUzI1NiIsImtpZCI6ImNsb2Q0aGtqejAya3AwMWozdWNqbzJwOHIiLCJ0eXAiOiJKV1QifQ.eyJhcGlUb2tlbklkIjoiY21kMmM0NGpkMXZ5NzAxcHZqaGtqZ3IzdSIsImF1ZCI6ImFzdHJvbm9tZXItZWUiLCJpYXQiOjE3NTI0NTEwNjAsImlzQXN0cm9ub21lckdlbmVyYXRlZCI6dHJ1ZSwiaXNJbnRlcm5hbCI6ZmFsc2UsImlzcyI6Imh0dHBzOi8vYXBpLmFzdHJvbm9tZXIuaW8iLCJraWQiOiJjbG9kNGhranowMmtwMDFqM3Vjam8ycDhyIiwicGVybWlzc2lvbnMiOlsiYXBpVG9rZW5JZDpjbWQyYzQ0amQxdnk3MDFwdmpoa2pncjN1Iiwib3JnYW5pemF0aW9uSWQ6Y21jcm4xM2NjMW1ydDAxbHlubXdncTYxdiIsIm9yZ1Nob3J0TmFtZTpjbWNybjEzY2MxbXJ0MDFseW5td2dxNjF2Il0sInNjb3BlIjoiYXBpVG9rZW5JZDpjbWQyYzQ0amQxdnk3MDFwdmpoa2pncjN1IG9yZ2FuaXphdGlvbklkOmNtY3JuMTNjYzFtcnQwMWx5bm13Z3E2MXYgb3JnU2hvcnROYW1lOmNtY3JuMTNjYzFtcnQwMWx5bm13Z3E2MXYiLCJzdWIiOiJjbWNybjAzcDYxbHZtMDFvaXQ1YjlhMzNhIiwidmVyc2lvbiI6ImNtZDJjNDRqZDF2eTYwMXB2cm4xNnNyY3MifQ.npabi78KBPL0goJ5ClUicV5H7vQH2ZOWTV2b0en3yjaponIHlLXoRsMuFLkwbLZeloEXRis-bFUAc3xFpkRtTT1RTnsdK7zD6mvq9qT1JL_hPc9C-uDDpNieJzzU5caMBwovRuKS-5q79593k9zzThqqaPH-hyL-9e_vn8Pw5hAWQO4YL1c5X-9Vwp8PHkLY99DUfDJZE0a8kv2sx-K7sMU9RsoVHv2RKZMkm8yvsdQGl6AHJ9yYwAP4ITuzWmmxtLZdqBeeU1BQlJKMNbK2vgOjA8kROGG-si-padbTu-hsPBuR2t3lGXN2DnTF8BWKy4ICuc1Zpe2rsy_QvOWCNQ
        deployment-id: arn:aws:iam::111928029897:role/astro-adiabatic-arc-8729
