name: Deploy to Astronomer
on:
  push:
    branches: [main]
env:
  ASTRO_API_TOKEN: ${{ secrets.ASTRO_API_TOKEN }}  # Your API token as a GitHub secret
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Deploy to Astro
      uses: astronomer/deploy-action@v0.10.1
      with:
        deployment-id: arn:aws:iam::111928029897:role/astro-adiabatic-arc-8729
